name: Deploy documentation

on:
  push:
    tags:
      - v*

jobs:
  deploy-typedoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Generate doc
      run: |
        npm ci
        npm run doc
        mv docs/documentation/html aave-v3-aptos-ts-sdk
    - name: Deploy files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.AAVEDOC_HOST }}
        username: ${{ secrets.AAVEDOC_USERNAME }}
        key: ${{ secrets.AAVEDOC_SSHKEY }}
        source: "./aave-v3-aptos-ts-sdk"
        target: "/var/www/type-doc"
