name: NPM Publish

on:
  release:
    types: [created]

jobs:
  test:
    uses: ./.github/workflows/node.js.yml

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Update npm
        shell: bash
        run: npm install -g npm@11.6.0

      - name: Enable Corepack
        run: corepack enable

      - name: Get PNPM store directory
        shell: bash
        run: |
          echo "STORE_PATH=$HOME/.local/share/pnpm/store" >> $GITHUB_ENV

      - name: Setup PNPM cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Extract tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run publish script
        run: ./scripts/publish.sh ${{ steps.get_tag.outputs.TAG }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/bundle.js
            dist/bundle.min.js
